object IntError 
  fn foo(): Int(true) = { 42 }
end IntError