object LetError2
  fn test(): Int(32) = {
    val x: Int(32) = false;
    2
  }
end LetError2
