object IntError 
  fn foo(): Int = { 42 }
end IntError